<?xml version="1.0" encoding="UTF-8"?>
<project
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd"
	xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
	<modelVersion>4.0.0</modelVersion>
	<groupId>org.eclipse.rmf</groupId>
	<artifactId>parent</artifactId>
	<version>1.0.0-SNAPSHOT</version>
	<packaging>pom</packaging>
	<properties>
		<eclipse.release>2020-03</eclipse.release>
	</properties>
	<modules>
		<!-- Release Engineering -->
<!--		<module>org.eclipse.rmf.releng.repository</module>-->

		<!-- ReqIF Core -->
		<module>org.eclipse.rmf.reqif10</module>
		<module>org.eclipse.rmf.reqif10.edit</module>
		<module>org.eclipse.rmf.reqif10.xhtml</module>
		<module>org.eclipse.rmf.reqif10.xhtml.edit</module>
		<module>org.eclipse.rmf.reqif10.common</module>
		<module>org.eclipse.rmf.reqif10.serialization</module>

		<module>org.eclipse.rmf.ext.prostep</module>

<!--		<module>org.eclipse.rmf.reqif10.feature</module>-->
<!--		<module>org.eclipse.rmf.reqif10.thirdparty.feature</module>-->
<!--		<module>org.eclipse.rmf.reqif10.sdk.feature</module>-->
		<!--	<module>org.eclipse.rmf.tests.serialization</module>-->
		<!--	<module>org.eclipse.rmf.tests.reqif10.serialization</module>-->
		<!--	<module>org.eclipse.rmf.tests.reqif10.common</module>-->
		<!--	<module>org.eclipse.rmf.tests.reqif10.constraints</module>-->
		<!--	<module>org.eclipse.rmf.tests.ext.prostep</module>-->
		<!--	<module>org.eclipse.rmf.tests.reqif10.feature</module>-->

		<!-- ReqIF UI ProR -->
		<module>org.eclipse.rmf.reqif10.pror</module>
		<module>org.eclipse.rmf.reqif10.pror.edit</module>
		<module>org.eclipse.rmf.reqif10.pror.editor</module>
		<!--	<module>org.eclipse.rmf.reqif10.pror.editor.tests</module>-->
		<module>org.eclipse.rmf.reqif10.pror.presentation.headline</module>
		<module>org.eclipse.rmf.reqif10.pror.presentation.id</module>
		<module>org.eclipse.rmf.reqif10.pror.presentation.linewrap</module>
		<module>org.eclipse.rmf.reqif10.search</module>
		<module>org.eclipse.rmf.reqif10.search.edit</module>
		<module>org.eclipse.rmf.reqif10.search.ui</module>
		<!--	<module>org.eclipse.rmf.reqif10.search.test</module>-->
		<module>org.eclipse.rmf.cheatsheets</module>
		<module>org.eclipse.rmf.reqif10.pror.genhtml</module>
		<module>org.eclipse.rmf.reqif10.csv.importer</module>
<!--		<module>org.eclipse.rmf.reqif10.pror.feature</module>-->
<!--		<module>org.eclipse.rmf.reqif10.pror.sdk.feature</module>-->

		<!-- Validator -->
		<module>org.eclipse.rmf.reqif10.constraints</module>
		<module>org.eclipse.rmf.reqif10.constraints.ui</module>
		<module>org.eclipse.rmf.reqif10.constraints.validator</module>
		<module>org.eclipse.rmf.reqif10.headlessValidator</module>

		<!-- 3rd Party Dependencies -->
		<module>org.agilemore.agilegrid</module>

		<!--	<module>org.eclipse.rmf.reqif10.pror.tests</module>-->
		<!-- <module>org.eclipse.rmf.reqif10.pror.presentation.id.tests</module> -->

		<!-- RMF Examples Plugins -->
<!--		<module>org.eclipse.rmf.examples.installer</module>-->
<!--		<module>org.eclipse.rmf.examples.feature</module>-->
	</modules>

	<repositories>
		<repository>
			<id>eclipse-release</id>
			<layout>p2</layout>
			<url>https://download.eclipse.org/releases/${eclipse.release}/</url>
		</repository>
<!--		<repository>-->
<!--			<id>eclipse-orbit</id>-->
<!--			<layout>p2</layout>-->
<!--			<url>https://download.eclipse.org/tools/orbit/simrel/orbit-aggregation/${eclipse.release}/</url>-->
<!--		</repository>-->
		<repository>
			<id>sphinx</id>
			<layout>p2</layout>
			<url>http://download.eclipse.org/sphinx/releases/0.9.x/</url>
		</repository>
		
	</repositories>

	<build>
		<plugins>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>tycho-maven-plugin</artifactId>
				<version>${tycho-version}</version>
				<extensions>true</extensions>
			</plugin>
			<plugin>
				<groupId>org.eclipse.tycho</groupId>
				<artifactId>target-platform-configuration</artifactId>
				<version>${tycho-version}</version>
				<configuration>
					<executionEnvironment>JavaSE-1.8</executionEnvironment>
				</configuration>

			</plugin>
		</plugins>
	</build>
</project>